export function formatSessionCommandsHelp(): string {
  return [
    'Gantry commands',
    '',
    'Session',
    '/commands - List available chat commands.',
    '/new - Start a fresh session while preserving durable memory and approved capabilities.',
    '/compact - Compact the current provider context and collect durable memory.',
    '/stop - Stop the active run for this conversation.',
    '',
    'Models',
    '/model - Show the current model selection.',
    '/model <alias> - Set the conversation model override.',
    '/model default - Clear the conversation model override.',
    '/models - List available model aliases.',
    '',
    'Status',
    '/status - Show model/runtime status for this conversation.',
    '/memory-status - Show durable memory status.',
    '/dream - Run memory dreaming now when enabled.',
    '',
    'Thinking',
    '/thinking - Show the current thinking setting.',
    '/thinking <low|medium|high|max|adaptive|enabled|off> - Set thinking for this conversation.',
    '/thinking default - Clear the thinking override.',
    '',
    'Memory',
    '/save-procedure "<title>" - Save reusable procedure steps from the message body or recent context.',
    '',
    'In-house agent surfaces',
    'gantry-admin - Runtime administration reference for approved Gantry admin tools.',
    'gantry-browser - Browser gateway guidance when the Browser capability is selected.',
  ].join('\n');
}
